configuration:
  working_directory: /tmp/ytdl-sub-working-directory
  file_name_max_bytes: 255
  persist_logs:
    keep_successful_logs: true
    logs_directory: /config/logs
  lock_directory: /tmp
presets:
  canales-youtube-ramon-alvarez-de-mon-ramonalvarezdemon:
    preset:
    - Jellyfin TV Show by Date
    - Max 720p
    - Only Recent
    overrides:
      enable_throttle_protection: false
      tv_show_directory: /downloads/Canales-youtube
    embed_thumbnail: true
  podcast-entrevistas-geoestratego-oficial:
    preset:
    - Only Recent
    - Filter Duration
    - Max MP3 Quality
    overrides:
      enable_throttle_protection: false
    embed_thumbnail: true
    output_options:
      output_directory: /downloads/Podcast/{subscription_root_sanitized}/{source_target_sanitized}
      file_name: '{title_sanitized}.{ext}'
      maintain_download_archive: true
    download: '{url}'
    audio_extract:
      enable: true
      codec: mp3
      quality: 0
  podcast-entrevistas-pl01fnqnul7ykui7id1lwxkz8ho3j8l8of:
    preset:
    - Only Recent
    - Filter Duration
    - Max MP3 Quality
    overrides:
      enable_throttle_protection: false
    embed_thumbnail: true
    output_options:
      output_directory: /downloads/Podcast/{subscription_root_sanitized}/{source_target_sanitized}
      file_name: '{title_sanitized}.{ext}'
      maintain_download_archive: true
    download: '{url}'
    audio_extract:
      enable: true
      codec: mp3
      quality: 0
  tv-serie-lolete-kerios:
    preset:
    - Jellyfin TV Show by Date
    - Max 1080p
    - Only Recent
    - Filter Duration
    overrides:
      enable_throttle_protection: false
      tv_show_directory: /downloads/TV-Serie
    embed_thumbnail: true
    ytdl_options:
      merge_output_format: mp4
  tv-serie-lolete-nickdaboom:
    preset:
    - Jellyfin TV Show by Date
    - Max 720p
    - Only Recent
    - Filter Duration
    overrides:
      enable_throttle_protection: false
      tv_show_directory: /downloads/TV-Serie
    embed_thumbnail: true
    ytdl_options:
      merge_output_format: mkv
  music-playlist-music-playlist-prueba-plcajstgncmdxgfdpc5aenevprzgcr-kut:
    preset:
    - Max MP3 Quality
    overrides:
      enable_throttle_protection: false
    embed_thumbnail: true
    output_options:
      output_directory: /downloads/Music-Playlist/{subscription_root_sanitized}
      file_name: '{title_sanitized}.{ext}'
      maintain_download_archive: true
    download: '{url}'
    audio_extract:
      enable: true
      codec: mp3
      quality: 0
  ambience-video-ambience-video-prueba-vr4savpspea:
    preset:
    - Max 720p
    overrides:
      enable_throttle_protection: false
    embed_thumbnail: false
    output_options:
      output_directory: /downloads/Ambience-Video/{subscription_root_sanitized}
      file_name: '{title_sanitized}.{ext}'
      maintain_download_archive: true
    download: '{url}'
    ytdl_options:
      merge_output_format: mp4
  ambience-audio-ambience-audio-prueba-gr-vejtzbso:
    preset: []
    overrides:
      enable_throttle_protection: false
    embed_thumbnail: false
    output_options:
      output_directory: /downloads/Ambience-Audio/{subscription_root_sanitized}
      file_name: '{title_sanitized}.{ext}'
      maintain_download_archive: true
    download: '{url}'
    audio_extract:
      enable: true
      codec: mp3
      quality: 0
